# Generated by Django 5.2.2 on 2025-06-14 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classsession',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='classsession',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='classsession',
            name='session_date',
        ),
        migrations.RemoveField(
            model_name='classsession',
            name='start_time',
        ),
        migrations.CreateModel(
            name='Teaches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.instructor')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subject')),
            ],
            options={
                'unique_together': {('instructor', 'subject')},
            },
        ),
    ]
