# Generated by Django 5.2.2 on 2025-06-16 02:41

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_remove_classsession_academic_year_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsession',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2025, 6, 16, 2, 41, 55, 990064, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='classsession',
            name='weekday',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='classsession',
            name='weeks_count',
            field=models.IntegerField(default=12),
        ),
        migrations.CreateModel(
            name='SessionDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField()),
                ('class_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.classsession')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', 'Present'), ('late', 'Late'), ('absent', 'Absent')], default='absent', max_length=10)),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student')),
                ('session_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.sessiondate')),
            ],
            options={
                'unique_together': {('student', 'session_date')},
            },
        ),
    ]
