name: attendance_system
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.8.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  jwt_decoder: ^2.0.1
  shared_preferences: ^2.2.3
  file_picker: ^10.2.0 
  cupertino_icons: ^1.0.8
  flutter_secure_storage: ^8.0.0 
  intl: ^0.19.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

